---
- name: MongoDB OS Best Practice Configuration (Percona 8.x)
  hosts: mongo
  become: yes
  gather_facts: yes

  vars:
    device_name: "/dev/sdb"   # data diskinin ismi (ör: /dev/sdb)

  pre_tasks:
    - name: Ensure prerequisite packages
      apt:
        name:
          - numactl
          - util-linux
          - chrony
        state: present
        update_cache: yes

  tasks:
    # 1) Swappiness
    - name: Set vm.swappiness=1 in sysctl.conf
      sysctl:
        name: vm.swappiness
        value: 1
        state: present
        reload: yes

    # 2) NUMA (bilgi amaçlı)
    - name: Check NUMA status
      command: numactl --hardware
      register: numa_status
      changed_when: false

    # 3) Zone reclaim mode
    - name: Set vm.zone_reclaim_mode=0
      sysctl:
        name: vm.zone_reclaim_mode
        value: 0
        state: present
        reload: yes

    # 4) Transparent Huge Pages disable (THP)
    - name: Create systemd unit to disable Transparent Huge Pages (THP)
      copy:
        dest: /etc/systemd/system/disable-transparent-huge-pages.service
        content: |
          [Unit]
          Description=Disable Transparent Huge Pages (THP)
          DefaultDependencies=no
          After=sysinit.target local-fs.target
          Before=mongod.service

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/bin/sh -c '\
            for f in /sys/kernel/mm/transparent_hugepage/enabled \
                     /sys/kernel/mm/transparent_hugepage/defrag; do \
              [ -f "$f" ] && echo never > "$f"; \
            done'

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd
        - Enable and start THP disable service

    - name: Apply THP setting immediately (runtime)
      shell: |
        [ -e /sys/kernel/mm/transparent_hugepage/enabled ] && echo never > /sys/kernel/mm/transparent_hugepage/enabled
        [ -e /sys/kernel/mm/transparent_hugepage/defrag ]  && echo never > /sys/kernel/mm/transparent_hugepage/defrag
      args:
        executable: /bin/bash

    # 5) Dirty ratio settings
    - name: Set dirty ratios
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { name: 'vm.dirty_ratio', value: 15 }
        - { name: 'vm.dirty_background_ratio', value: 5 }

    # 6) Network stack tuning
    - name: Apply network stack settings
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { name: 'net.core.somaxconn', value: 4096 }
        - { name: 'net.ipv4.tcp_fin_timeout', value: 30 }
        - { name: 'net.ipv4.tcp_keepalive_intvl', value: 30 }
        - { name: 'net.ipv4.tcp_keepalive_time', value: 120 }
        - { name: 'net.ipv4.tcp_max_syn_backlog', value: 4096 }
        - { name: 'net.ipv4.tcp_keepalive_probes', value: 6 }

    # 7) Time sync kontrolü
    - name: Ensure NTP or timesync service is active
      shell: |
        systemctl is-active chronyd || systemctl is-active systemd-timesyncd
      register: ntp_status
      changed_when: false
      failed_when: false

    - name: Print NTP service status
      debug:
        msg: "NTP service status: {{ ntp_status.stdout | default('unknown') }}"

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Enable and start THP disable service
      systemd:
        name: disable-transparent-huge-pages.service
        enabled: yes
        state: started

    # 5) Max Map Count settings
    - name: Set vm.max_map_count
      sysctl:
        name: vm.max_map_count
        value: 262144
        state: present
        reload: yes
